workflows:
  my-workflow:
    triggering:
      events:
        - push
      branch_patterns: 
        - pattern: *
        - pattern: develop
          include: false
      cancel_previous_builds: true
    scripts:
      - sleep(1000)
